ext_if = "vtnet0"

set skip on lo
block in all
pass out all

# WireGuard
pass in quick on $ext_if proto udp from any to any port 51820
# SSH
pass in quick on $ext_if proto tcp from any to any port 22

# Log all blocked packets
block in log on $ext_if all
